
import React from 'react';
import { APP_TITLE } from '../constants';

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-secondary-lt dark:bg-secondary text-muted-text-lt dark:text-muted-text py-8 mt-auto border-t border-border-light dark:border-border-dark transition-colors duration-300">
      <div className="container mx-auto px-4 text-center">
        <p className="text-sm">
          &copy; {currentYear} {APP_TITLE}. All rights reserved.
        </p>
        <p className="text-xs mt-1">
          Wallpapers generated by AI. Design by Vijaykoushik, S..
        </p>
        <p className="text-xs mt-2">
            <a href="https://github.com/your-username/artscapes-ai" target="_blank" rel="noopener noreferrer" className="hover:text-accent dark:hover:text-accent-lt transition-colors">
                View Source on GitHub
            </a>
        </p>
      </div>
    </footer>
  );
};

export default Footer;
